# Generated by Django 4.1.7 on 2023-03-15 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_variationmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariationManager',
        ),
    ]
